services:
  ollama:
    image: ollama/ollama:0.4.7
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    volumes:
      - ${HOME}/.ollama:/root/.ollama
    ports:
      - '11434:11434'

  chromadb:
    image: chromadb/chroma:0.5.21
    restart: unless-stopped
    volumes:
      - chromadb-data:/chroma/chroma
    ports:
      - '8000:8000'

  dagster-db:
    image: bitnami/postgresql:16.6.0
    restart: unless-stopped
    env_file: .env
    volumes:
      - dagster-db-data:/bitnami/postgresql

  dagster:
    build: .
    image: kvdomingo/genai-lab-dagster
    restart: unless-stopped
    init: true
    command: [ /app/docker-entrypoint.sh ]
    env_file: .env
    environment:
      CHROMA_HOST: chromadb
      OLLAMA_URL: http://ollama:11434
    volumes:
      - .:/app
      - ./dagster.yaml:/opt/dagster/dagster.yaml
      - ${HOME}/obsidian:/opt/obsidian
      - dagster-venv-data:/app/.venv
    ports:
      - '3030:3030'

volumes:
  chromadb-data:
  dagster-db-data:
  dagster-venv-data:
