services:
  ollama:
    image: ollama/ollama:0.3.14
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ollama:/root/.ollama
    ports:
      - '11434:11434'

volumes:
  ollama:
