services:
  ollama:
    image: ollama/ollama:0.3.14
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    volumes:
      - ${HOME}/.ollama:/root/.ollama
    ports:
      - '11434:11434'

  chromadb:
    image: chromadb/chroma:0.5.17
    restart: unless-stopped
    ports:
      - '8000:8000'
